### ISSUE TITLE
Change Keybind

### ISSUE THREAD

**Issue by Dommezzx** [Draylar/identity#102]
I`m looking for a way to change keybind because I`m using a nordic keyboard and to open the menu I have to press shift+ ` but because of me holding shift I can`t open it. Can I change it?

**Comment by Dommezzx** [comment]
I don´t know why but I can´t type ` in the bug report

**Comment by Draylar** [comment]
Yes, it is the same process as any other keybind: open options, find the Identity swap key (set to \`), and change it to something else. The current release doesn't have a translation key for options, so you can find it under the gameplay category as "`key.identity`".

I'll push an update in a second that translates the options (to make them human-readable) and put them in a separate category.

You're having issues typing the \` key because it is also used `for code formatting`. To properly type it out, you can prefix it with a \\, like so:

\\`

Let me know if you encounter any other issues while changing the keybind.
