### ISSUE TITLE
Can't use abilities

### ISSUE THREAD

**Issue by Daeviin** [Draylar/identity#125]
**Bug description**
I tried pressing r, alt-r, function-r, but nothing works.Please help I have been wanting to use this mod for a very long time now. :D Thanks.

**Comment by James103** [comment]
1. You need to be on the latest version of Identity mod in order to use abilities with hotkeys. Update Identity to 1.11.4 and Minecraft to 1.16.4, then try and use the ability key (which is just `R` by default).
2. You need to be disguised as an entity that has abilities (ghast, creeper, blaze, enderman, snow golem, ender dragon, or wither).
