### ISSUE TITLE
Ability to restrict mod to certain permissions on server?

### ISSUE THREAD

**Issue by M1necraftL0rd** [Draylar/identity#154]
Is it possible to restrict the mod to a certain permission group on a server? Or can I only restrict it to admins/operators?

**Comment by Draylar** [comment]
Fabric doesn't have a concept of permission groups, but you can disable the mod for anyone without OP by disabling the menu for players. I could add an option to only enable the menu for operators, if that is what you are looking for?

**Comment by M1necraftL0rd** [comment]
I meant more from an operator's standpoint on a server: would I be able to restrict use of the mod to anyone outside of a permission group, making use of a permissions plugin, or is that not possible with the mod? I am not sure how well fabric works with plugins or stuff like that.

**Comment by Draylar** [comment]
If a permission plugin existed, it would be _possible_ to provide compatibility with additional work, but the current phase of the project doesn't support anything like that (because Fabric does not have ""permissions"" built-in; it would have to be a 3rd-party library with external capabilities, and I can't name any libraries/projects that fit the bill for that). 

If anything, it would be a separate extension mod built specifically for Identity that hooks into permission mods. I would be happy to look into it if you have a particular permissions library/system you are already using.
