### ISSUE TITLE
killing an entity with a bare-hand custom attack dose not grant identity

### ISSUE THREAD

**Issue by MimzyFang** [Draylar/identity#161]
**Bug description**
when killing an entity with a identity that has a bare-hand custom attack you don't unlock it <br> same with the forceChange options if you kill an entity with your hand you are not changed in to it 

**Game log:**
[paste.ee](https://paste.ee/p/qr3n5) hastebin was not able to save my log so i auto uplodet it with multimc

**Comment by MimzyFang** [comment]
i looked further into it bare-hand custom attacks are not counted as a mob kill at all
here is a video of this 
https://streamable.com/hu1929

**Comment by Fauli1221** [comment]
i made a video to showcase the bug
https://streamable.com/hu1929

**Comment by AllanChain** [comment]
Possibly because `attacker` is the identity, not instance of `PlayerEntity`

https://github.com/Draylar/identity/blob/35c1f20759909ba8deab303463cfba960df83cb1/src/main/java/draylar/identity/mixin/PlayerEntityAttackMixin.java#L30

https://github.com/Draylar/identity/blob/35c1f20759909ba8deab303463cfba960df83cb1/src/main/java/draylar/identity/mixin/LivingEntityMixin.java#L52

But how to know whose current identity is the attacker?
