### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by RaduJR32** [Draylar/identity#163]
when i kill a mob its says identity.unlock_entity what should i do ? and it doesnt do me a mob

**Comment by James103** [comment]
Can you retry with a fresh installation of the following setup?
* Minecraft 1.16.5
* Fabric Loader (latest version)
* Fabric API 0.30+
* Identity 1.11.9

**Comment by RaduJR32** [comment]
i have the mod on 1.16.5 with the fabric loader already

**Comment by RaduJR32** [comment]
ima try

**Comment by Draylar** [comment]
Are you using a non-English language in your game? If you do not see the mob in the menu after killing it, please upload your game log to [pastebin](https://pastebin.com/).

**Comment by RaduJR32** [comment]
i dont have a menu and i use English language in my game

**Comment by RaduJR32** [comment]
guys i reinstalled the fabric,version and i am setting the mod

**Comment by RaduJR32** [comment]
`yea its not working

**Comment by RaduJR32** [comment]
https://pastebin.com/GWbTcxzL
the log link

**Comment by Draylar** [comment]
That game log is from a dedicated server, correct? Are you using Aternos as a host, by any chance? Do all the clients connecting to the server also have the mod installed? Please provide the client log as well (the server log is fine, nothing out of the ordinary).

edit: this definitely sounds like not having the mod installed on the client, due to the translation key not being present (but still showing), and the menu keybind not working.

**Comment by RaduJR32** [comment]
Yea the host its aternos, i have the mod installed and all the clients are connecting to the server

**Comment by RaduJR32** [comment]
Do you have an aternos account ?  I will give u acces to the server to help me if u want and see the error

**Comment by RaduJR32** [comment]
RDU2201.aternos.me

**Comment by Draylar** [comment]
Aternos is notorious for breaking Identity. I'm not sure what they are doing, but it is something outside my control. It's probably a restriction on what packets mods can send... or something of that sort. I'm happy to look at other server logs if anything looks off, but I don't think I can solve this issue on my end.

edit: that is to say, I'm happy to fix the issue if anyone has any ideas, but I am almost certain Aternos is to blame, because this only occurs _exclusively_ on Aternos across all similar reports I have received.
