### ISSUE TITLE
Work

### ISSUE THREAD

**Issue by Sage456123** [Draylar/identity#218]
I really want to work with you @Draylar , I will be very very very happy and hard working if you accept me please! :(((

**Comment by Draylar** [comment]
Please restrain yourself from opening more not-an-issue issue posts-- the previous ones work fine, and you can comment on those if you need to reach out. While I appreciate the suggestions, I have work, school, responsibilities outside this mod, and other projects, so you are going to have to wait longer than 20 hours for me to implement them.

I generally work on my mods in a circular pattern. Because the last Identity release was 10 days ago, I expect to come back to implement a few more suggestions within 10 days. If you want to help out, the best thing you can do is suggest features with additional details, or report bugs with as much info as possible (game logs, screenshots, versions). This makes it easier for me to add to the game when the time comes.
