### ISSUE TITLE
Game seems to crash and give an exit code 0 if I have both Origins and Identity installed.

### ISSUE THREAD

**Issue by beautiful-lunatic** [Draylar/identity#241]
The new update 1.17 seems to cause Origins and Identity to be incompatible and causes the game to crash if I try to run it.

**Comment by ScottWDeane** [comment]
I can confirm, I get the same thing. Using Origins and Identity at the same time causes a crash back to the mc launcher (with no crash log?).

Once I remove Origins, Identity works.

**Comment by apace100** [comment]
Hi! I tracked this bug down to being related to FallFlyingLib (a library mod which is included in Origins). I posted an issue on their GitHub (https://github.com/CafeteriaGuild/FallFlyingLib/issues/9). 

The issue seems to be that both Identity and FFL use an `EntityAccessor` mixin with an accessor to the `setFlag` method.

I attached the error of the crash if you need it: [identitycrash.log](https://github.com/CafeteriaGuild/FallFlyingLib/files/6688410/identitycrash.log)

Thanks!

**Comment by beautiful-lunatic** [comment]
> Hi! I tracked this bug down to being related to FallFlyingLib (a library mod which is included in Origins). I posted an issue on their GitHub ([CafeteriaGuild/FallFlyingLib#9](https://github.com/CafeteriaGuild/FallFlyingLib/issues/9)).
> 
> The issue seems to be that both Identity and FFL use an `EntityAccessor` mixin with an accessor to the `setFlag` method.
> 
> I attached the error of the crash if you need it: [identitycrash.log](https://github.com/CafeteriaGuild/FallFlyingLib/files/6688410/identitycrash.log)
> 
> Thanks!

Did you ever get the game to run when having them both installed?

**Comment by Draylar** [comment]
Oh, I fixed this in yesterday's quick update (1.14.2-beta). Let me know if the problem persists after updating.

**Comment by beautiful-lunatic** [comment]
> Oh, I fixed this in yesterday's quick update (1.14.2-beta). Let me know if the problem persists after updating.

I got it to work! thanks so much!
