### ISSUE TITLE
Crashes on Morph

### ISSUE THREAD

**Issue by trolol12** [Draylar/identity#299]
Everytime I load up a world, kill a mob and try to morph into said mob the game crashes. And anytime I try to load the world back up, it crashes

Crash - https://hastebin.com/uwadaxohuc.yaml

Log - https://hastebin.com/heyatotexu.yaml

**Comment by James103** [comment]
Converted the pasts to text files as the pastes expire in only a few days:
[crash-report.txt](https://github.com/Draylar/identity/files/7413120/crash-report.txt)
[latest.log](https://github.com/Draylar/identity/files/7413121/latest.log)

**Comment by DatrixTHLK** [comment]
I get this same error morphing into a bat. It just crashes me to the main menu while telling me it booted me from the multiplayer server when I play single player only.

**Comment by Draylar** [comment]
I'm guessing this is a recent issue with Fabric API or Mixin[???], because:

1. This issue just popped up on both the 1.17.1 & 1.16 branches, which have been working fine up till now
2. Requiem [has an identical crash](https://github.com/Ladysnake/Requiem/issues/440) caused by the same Mixin inheritance style from the past week
3. This crash occurs on all the mixins that use this style

I did some poking around but can only seem to reproduce it in production. I don't care enough to find the exact underlying issue, so I'm just going to change the style around to avoid the offending problem. This fix seems to work for me, but let me know if you encounter it again (might've missed 1 or 2 instances in other classes of this).

=> https://github.com/Draylar/identity/releases/tag/1.15.2-1.17.1-fabric
