### ISSUE TITLE
Identities disappear on reconnect

### ISSUE THREAD

**Issue by oliver408i** [Draylar/identity#323]
**Bug description**
When you leave and reconnect, sometimes the identities disappear, if you disconnected with an identity equiped. You can fix the issue by killing an animal, dying, going through a nether portal. This is on a server.

Game does not crash

**Comment by Draylar** [comment]
This should:tm: be fixed in the 2.1.0 alpha Forge version, which I will release tonight (a few hours from this post). I would appreciate it if you gave the new version a try and let me know how it goes! It should have much better syncing when going through portals and disconnecting. 

![image](https://user-images.githubusercontent.com/17728338/149245680-4c5b77e6-d4b6-40d1-8892-fada5ddfbb0d.png)
