### ISSUE TITLE
Make the mod ignore the following server tags (disable abilities) if the server is not a fabric/forge server.

### ISSUE THREAD

**Issue by NPC-Master3304** [Draylar/identity#333]
to keep this short, back when the morph mod was released in 1.6.4, you were able to join any servers. Obviously since the server didn't have the mod itself, you could only use it for looks (plus back then there weren't abilities). I was wondering if you could make it to where it would ignores the un-vanilla server tags and the abilities for servers that aren't fabric or forge like how it was in the original version. since you wanted to bring back the old morph mod, this was one key feature that this newer version lacks. Plus, this would allow people to use it more since they could use it on servers that they liked if they wanted to change their player model on their end (I changed myself to a zombie since it was 2 blocks tall as it didn't cause major issues). I was thinking about editing the source code myself, but I think that if I made this a bug, you could implement it as a official feature than me just modding it for myself.

_Incomplete set of tags received from server.
Please contact server operator._
`[16:58:20] [Render thread/WARN]: Incomplete server tags, disconnecting. Missing: {ResourceKey[minecraft:root / minecraft:entity_type]=[identity:slow_falling, identity:undrownable, identity:wolf_prey, identity:hurt_by_high_temperature, identity:ravager_riding, identity:burns_in_daylight, identity:lava_walking, identity:cant_swim, identity:piglin_friendly, identity:fox_prey, identity:flying]}`

**Comment by Draylar** [comment]
Even if the mod could be loaded on a server such as Hypixel without matching tags, Identity would not work (right now:tm:). The mod revolves around the client requesting a swap from the server - "hey, I clicked the Creeper button, please let me switch..." - and the server sending back a packet saying "okay, request received, you are good to swap." Even if you could load the menu on the client, the server not responding to packet requests means you would not see any change on the client.

For the time being, you could fork Identity and make changes to allow this (you can make `EntityWidget` set the client's Identity directly instead of sending a packet).

---

While I don't plan to support either of these by default natively, I can add a config option on the client which allows you to join servers without matching tag files, as well as (potentially) one to implement the above client-side fix, because I don't want to make it impossible to at least try. No promises on timing, but I will look into it during the next update :)

**Comment by NPC-Master3304** [comment]
o alr. :)
i wish u luck if u can manage to get it working
