### ISSUE TITLE
iron golem

### ISSUE THREAD

**Issue by BoniH1908** [Draylar/identity#345]
the iron golem can regenarate infinitly and gets unlimited hearts

**Comment by AllanChain** [comment]
@Draylar , I'm trying to solve this issue but confused about some of the code.

Why do we need to modify `maxHealth` since it's already modified in `IdentityComponent.java`? I tried to remove this inject and the problem was solved. But I'm unsure what it does.

https://github.com/Draylar/identity/blob/d6bade49a957fc5eaa42cdafca63dde9511728ab/src/main/java/draylar/identity/mixin/LivingEntityMixin.java#L176-L191

**Comment by Draylar** [comment]
Thanks for the info Allan - no idea why it was like that, but the issue should be fixed now! <3
