### ISSUE TITLE
How come swimming as a fish/turtle/dolphin/squid is still just as slow as players?

### ISSUE THREAD

**Issue by aaawertghgefwdq** [Draylar/identity#37]
In a YouTube video [https://www.youtube.com/watch?v=ZGpBd_Koplg&t=868s](url) the youtuber was able to swim faster as a fish, like they should (faster than a boat too), but in-game the fish and other aquatic animals are just as slow as players (I am on 1.16.1). Is this a bug, or am I doing something wrong?

Also, mining as a fish under water doesn't work either

**Comment by Draylar** [comment]
Identity hasn't provided that feature before; my guess is they have a custom data pack installed which was implementing that functionality. Notice how they always have the *Dolphin's Grace* status effect in the top right corner.

I say "before," because I just implemented it in 1.6.0, which will be out for 1.16.1 shortly. All Aquatic Creatures will have a swim speed buff now.

Would you mind clarifying on what doesn't work with mining as a fish? I just tested it out with a Pickaxe on stone, and everything (animations, drops, sounds) seemed to work fine.

**Comment by aaawertghgefwdq** [comment]
> Identity hasn't provided that feature before; my guess is they have a custom data pack installed which was implementing that functionality. Notice how they always have the _Dolphin's Grace_ status effect in the top right corner.
> 
> I say "before," because I just implemented it in 1.6.0, which will be out for 1.16.1 shortly. All Aquatic Creatures will have a swim speed buff now.
> 
> Would you mind clarifying on what doesn't work with mining as a fish? I just tested it out with a Pickaxe on stone, and everything (animations, drops, sounds) seemed to work fine.

That's okay! I was just making sure it wasn't just a bug for me. Also, as for clarification, I was a fish and I found an underwater mine with gold, and as I was trying to mine it It simply would not let me mine it at all. I was using an iron pickaxe, and since I kept trying I guess the effect stacked because the fatigue lasted for around 4 minutes.

**Comment by Draylar** [comment]
I'm going to close this because I think it has been fixed (and the fatigue for 4 minutes was probably an Elder Guardian). Feel free to re-open if you encounter the issue again.
