### ISSUE TITLE
Parrot Wings Doesn't Flap When Flying (Small Question, Different Colored Parrots In Future?)

### ISSUE THREAD

**Issue by ghost** [Draylar/identity#4]
Title mostly says it all,
![2020-06-25_15 16 30](https://user-images.githubusercontent.com/67247581/85801089-fc572100-b6f6-11ea-86bb-707c0a8cd7f5.png)

About the other question I was wondering, will we be able to morph into different colored parrots other than just one?

**Comment by Draylar** [comment]
Mostly fixed Parrots in 1.0.3 ([CF](https://www.curseforge.com/minecraft/mc-mods/identity/files/2988891), [GH](https://github.com/Draylar/identity/releases/tag/1.0.3-beta-1.16)). They're still a bit wonky due to... something, but it's better than nothing.

Regarding mob variants, it is something I would like to explore, but I need to think of a good way to do it first. I could provide extra options at the bottom of the morph screen for setting mob-specific data (eg. rainbow Parrot, or whatever).
