### ISSUE TITLE
cats are broken. legs do weird things. really bad when crouching

### ISSUE THREAD

**Issue by realflow100** [Draylar/identity#52]
https://cdn.discordapp.com/attachments/490759561977004032/777309049707954186/unknown.png

broken legs going through body.

The tail straightens out a little.  but i dont know if thats intentional or not.

crouching looks bad with a lot of mobs.

I wonder if its possible crouching without moving could cycle through different mob sitting or sleeping states. like wolf sit or fox sit or sleep ect.

**Comment by James103** [comment]
1. According to the screenshot, you are most likely running Windows 7 or more likely earlier. What OS are you actually running?
2. What version of Identity are you running?
3. If you are running any other mods, can you please list them with version info?

**Comment by realflow100** [comment]
1.16.3 identity-1.9.2-beta-1.16.3.jar
Windows 7 using windows classic theme
Only other mods are 
lithium-fabric-mc1.16.3-0.5.6.jar
phosphor-fabric-mc1.16.1-0.6.0+build.7.jar
sodium-fabric-mc1.16.3-0.1.0.jar

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/99193837-29a57980-2741-11eb-84af-805fdf5d40ee.png)

Cats fixed in next release, Ocelots don't seem to have a sitting animation

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/99204478-6c844300-277b-11eb-96a2-9ca3f7dca29d.png)

Biped entities have been fixed in the next release as well. All other entities will need to be special-cased, so please let me know of any other entities you find that have bad crouching animations.

For sub-types, I'm putting up an issue at #55. For rotating through poses, #56.
