### ISSUE TITLE
Identity sub-types

### ISSUE THREAD

**Issue by Draylar** [Draylar/identity#55]
Players should be able to transform into sub-types of an Identity, such as a tropical fish for the fish category, or a small slime for slimes.

**Comment by James103** [comment]
For example, you could be able to swap between different professions of Villager and/or Zombie Villager from the different biome types, as long as you have unlocked the relevant profession/biome combination before.

Or, you could have the three different types of Armor Stands: the standard model without arms, the model with arms, and a version of the model with arms that uses humanoid animations instead of just staying in one pose.

**Comment by bombaluriina** [comment]
I’m extremely interested in having this feature. The main reason I don’t really play this mod is because the cat and fox mobs only default to one variant

**Comment by ebbisis** [comment]
Has this been implemented ? #257 Suggests you just need to click the mob again in the menu after killing the new type.

**Comment by Draylar** [comment]
> Has this been implemented ? #257 Suggests you just need to click the mob again in the menu after killing the new type.

Not intentionally, I'm guessing that was just a funny quirk related specifically to Axolotols.
